workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      xcode: 16.4
      groups:
        - LiDarX   # APP_STORE_CONNECT_KEY_ID / APP_STORE_CONNECT_PRIVATE_KEY / APP_STORE_CONNECT_ISSUER_ID
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"      # se usar Pods/Workspace: "LiDarX.xcworkspace"
        XCODE_SCHEME: "LiDarX Agricultural"
        BUNDLE_ID: "com.agroneri.lidarx"
        APPLE_TEAM_ID: "M66N5P2D3F"

    scripts:
      - name: Diagnóstico rápido (opcional)
        script: |
          set -e
          if [[ "$XCODE_PROJECT" == *".xcworkspace" ]]; then PROJ=(-workspace "$XCODE_PROJECT"); else PROJ=(-project "$XCODE_PROJECT"); fi
          xcodebuild -list "${PROJ[@]}"
          xcodebuild -showdestinations "${PROJ[@]}" -scheme "$XCODE_SCHEME" || true

      - name: Corrigir Assets.xcassets (robusto)
        script: |
          set -e
          APP_DIR="$(ls -1d */ 2>/dev/null | sed 's:/$::' | while read d; do [ -f "$d/Info.plist" ] && { echo "$d"; break; }; done)"
          [ -z "$APP_DIR" ] && APP_DIR="LiDarX"
          [ -e "$APP_DIR" ] && [ ! -d "$APP_DIR" ] && mv "$APP_DIR" "${APP_DIR}.file_backup_$(date +%s)"
          mkdir -p "$APP_DIR"
          ASSETS_DIR="$APP_DIR/Assets.xcassets"
          [ -e "$ASSETS_DIR" ] && [ ! -d "$ASSETS_DIR" ] && mv "$ASSETS_DIR" "${ASSETS_DIR}.bak_$(date +%s)"
          mkdir -p "$ASSETS_DIR"
          if [ ! -f "$ASSETS_DIR/Contents.json" ]; then
            printf '%s\n' '{' '  "info": { "version": 1, "author": "xcode" }' '}' > "$ASSETS_DIR/Contents.json"
          fi
          echo "✅ Assets em: $ASSETS_DIR"

      - name: Buscar/gerar certificados e perfis (via App Store Connect)
        script: |
          set -e
          keychain initialize
          # Distribuição (App Store)
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create --team-id "$APPLE_TEAM_ID"
          # Desenvolvimento (opcional)
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create --team-id "$APPLE_TEAM_ID" || true
          # Aplicar perfis ao projeto/targets
          xcode-project use-profiles

      - name: Clean
        script: |
          set -e
          if [[ "$XCODE_PROJECT" == *".xcworkspace" ]]; then
            xcodebuild -workspace "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" clean || true
          else
            xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" clean || true
          fi

      - name: Archive (iPhoneOS, usando perfis aplicados)
        script: |
          set -e
          ARCH_PATH="$CM_BUILD_DIR/LiDarX.xcarchive"
          if [[ "$XCODE_PROJECT" == *".xcworkspace" ]]; then
            xcodebuild -workspace "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
              PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
              ASSETCATALOG_COMPILER_APPICON_NAME="" \
              archive -archivePath "$ARCH_PATH"
          else
            xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" \
              -configuration Release \
              -sdk iphoneos \
              DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
              PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
              ASSETCATALOG_COMPILER_APPICON_NAME="" \
              archive -archivePath "$ARCH_PATH"
          fi
          echo "✅ Archive: $ARCH_PATH"

      - name: Gerar ExportOptions.plist (manual)
        script: |
          set -e
          plist_path="$CM_BUILD_DIR/ExportOptions.plist"
          printf '%s\n' \
            '<?xml version="1.0" encoding="UTF-8"?>' \
            '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' \
            '<plist version="1.0">' \
            '<dict>' \
            '  <key>method</key><string>app-store</string>' \
            '  <key>signingStyle</key><string>manual</string>' \
            '  <key>uploadSymbols</key><true/>' \
            '  <key>compileBitcode</key><false/>' \
            '</dict>' \
            '</plist>' > "$plist_path"
          echo "✅ ExportOptions.plist: $plist_path"

      - name: Export .ipa (App Store)
        script: |
          set -e
          ARCH_PATH="$CM_BUILD_DIR/LiDarX.xcarchive"
          xcodebuild -exportArchive \
            -archivePath "$ARCH_PATH" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_EXPORT_DIR"
          echo "✅ IPA em: $CM_EXPORT_DIR"
          ls -lah "$CM_EXPORT_DIR"

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_BUILD_DIR/LiDarX.xcarchive
      - $HOME/Library/Logs/**/*
      - ~/Library/Developer/Xcode/DerivedData/**/Logs/**

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # beta_groups:
        #   - Internal Testing
        # app_id: $APP_STORE_APP_ID
