workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      xcode: 16.4
      groups:
        - LiDarX   # APP_STORE_CONNECT_KEY_ID / APP_STORE_CONNECT_PRIVATE_KEY / APP_STORE_CONNECT_ISSUER_ID
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"      # se usar Pods/Workspace: "LiDarX.xcworkspace"
        XCODE_SCHEME: "LiDarX Agricultural"
        BUNDLE_ID: "com.agroneri.lidarx"
        APPLE_TEAM_ID: "M66N5P2D3F"

    scripts:
      - name: Diagnóstico rápido (opcional)
        script: |
          set -e
          if [[ "$XCODE_PROJECT" == *".xcworkspace" ]]; then PROJ=(-workspace "$XCODE_PROJECT"); else PROJ=(-project "$XCODE_PROJECT"); fi
          xcodebuild -list "${PROJ[@]}"
          xcodebuild -showdestinations "${PROJ[@]}" -scheme "$XCODE_SCHEME" || true

      - name: Corrigir Assets.xcassets
        script: |
          set -e
          APP_DIR="$(ls -1d */ 2>/dev/null | sed 's:/$::' | while read d; do [ -f "$d/Info.plist" ] && { echo "$d"; break; }; done)"
          [ -z "$APP_DIR" ] && APP_DIR="LiDarX"
          [ -e "$APP_DIR" ] && [ ! -d "$APP_DIR" ] && mv "$APP_DIR" "${APP_DIR}.file_backup_$(date +%s)"
          mkdir -p "$APP_DIR"
          ASSETS_DIR="$APP_DIR/Assets.xcassets"
          [ -e "$ASSETS_DIR" ] && [ ! -d "$ASSETS_DIR" ] && mv "$ASSETS_DIR" "${ASSETS_DIR}.bak_$(date +%s)"
          mkdir -p "$ASSETS_DIR"
          if [ ! -f "$ASSETS_DIR/Contents.json" ]; then
            printf '%s\n' '{' '  "info": { "version": 1, "author": "xcode" }' '}' > "$ASSETS_DIR/Contents.json"
          fi
          echo "✅ Assets em: $ASSETS_DIR"

      - name: Buscar/gerar certificados e perfis (via App Store Connect)
        script: |
          set -e
          keychain initialize
          # Distribuição (App Store) -> cria/baixa cert + profile
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create --team-id "$APPLE_TEAM_ID"
          # Desenvolvimento (opcional) -> útil para compilar dependências que exigem dev profile
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT --create --team-id "$APPLE_TEAM_ID" || true
          # Aplicar perfis ao projeto/targets automaticamente
          xcode-project use-profiles

      - name: Clean
        script: |
          set -e
          if [[ "$XCODE_PROJECT" == *".xcworkspace" ]]; then
            xcodebuild -workspace "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" clean || true
          else
            xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" clean || true
          fi

      - name: Archive (iPhoneOS, usando perfis aplicados)
        script: |
          set -e
          ARCH_PATH="$CM_BUILD_DIR/LiDarX.xcarchive"
          if
