workflows:
  lidarx_ios:
    name: LiDarX iOS Build

    environment:
      xcode: 16.4
      groups:
        - LiDarX   # APP_STORE_CONNECT_* aqui dentro
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lidarx.agricultural
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"
        XCODE_SCHEME: "LiDarX Agricultural"
        BUNDLE_ID: "com.lidarx.agricultural"
        APPLE_TEAM_ID: "M66N5P2D3F"

    scripts:
      - name: Preparar Assets e LaunchScreen
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🔧 Preparando estrutura LiDarX..."

          APP_DIR="LiDarX"
          ASSETS_DIR="$APP_DIR/Assets.xcassets"
          LS_FILE="$APP_DIR/LaunchScreen.storyboard"

          if [ -e "$APP_DIR" ] && [ ! -d "$APP_DIR" ]; then
            echo "⚠️ '$APP_DIR' é um arquivo. Movendo para backup..."
            mv "$APP_DIR" "${APP_DIR}.backup_$(date +%s)"
          fi

          mkdir -p "$APP_DIR"

          if [ -e "$ASSETS_DIR" ] && [ ! -d "$ASSETS_DIR" ]; then
            echo "⚠️ '$ASSETS_DIR' não é diretório. Movendo para backup..."
            mv "$ASSETS_DIR" "${ASSETS_DIR}.backup_$(date +%s)"
          fi

          mkdir -p "$ASSETS_DIR"

          if [ ! -f "$ASSETS_DIR/Contents.json" ]; then
            echo '{"info":{"version":1,"author":"xcode"}}' > "$ASSETS_DIR/Contents.json"
            echo "✅ Contents.json criado"
          else
            echo "✅ Contents.json já existe"
          fi

          if [ ! -f "$LS_FILE" ]; then
            echo "📄 Criando LaunchScreen.storyboard..."
            echo '<?xml version="1.0" encoding="UTF-8"?><document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" targetRuntime="iOS.CocoaTouch"><scenes><scene sceneID="launch"><objects><viewController id="VC" sceneMemberID="viewController"><view key="view" id="view" backgroundColor="white"/></viewController></objects></scene></scenes></document>' > "$LS_FILE"
            echo "✅ LaunchScreen.storyboard criado"
          else
            echo "✅ LaunchScreen.storyboard já existe"
          fi

      - name: Configurar assinatura iOS
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🔐 Inicializando keychain e baixando perfis..."

          # Inicializa o keychain onde o Codemagic vai guardar os certificados
          keychain initialize

          # Baixa (ou cria) certificados + provisioning profile para o bundle id
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

          # Aplica os perfis no projeto Xcode (Signing & Capabilities)
          xcode-project use-profiles

          echo "✅ Assinatura configurada no projeto."

      - name: Clean
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🧹 Limpando projeto..."
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" clean || true

      - name: Archive
        script: |
          #!/usr/bin/env bash
          set -e
          echo "📦 Gerando archive..."
          ARCH_PATH="$CM_BUILD_DIR/LiDarX.xcarchive"

          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            archive -archivePath "$ARCH_PATH"

          echo "✅ Archive gerado em: $ARCH_PATH"

      - name: Gerar ExportOptions.plist
        script: |
          #!/usr/bin/env bash
          set -e
          echo "📝 Criando ExportOptions.plist..."
          PLIST="$CM_BUILD_DIR/ExportOptions.plist"
          echo '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>method</key><string>app-store</string><key>uploadSymbols</key><true/><key>compileBitcode</key><false/></dict></plist>' > "$PLIST"
          echo "✅ ExportOptions.plist criado em: $PLIST"

      - name: Export .ipa
        script: |
          #!/usr/bin/env bash
          set -e
          echo "📤 Exportando IPA..."
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/LiDarX.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_EXPORT_DIR"
          echo "✅ IPA gerado. Conteúdo do diretório:"
          ls -lah "$CM_EXPORT_DIR"

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_BUILD_DIR/LiDarX.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
