workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      xcode: 16.4
      groups:
        - LiDarX
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"      # troque por .xcworkspace se usar CocoaPods
        XCODE_SCHEME: "LiDarX Agricultural"
        BUNDLE_ID: "com.agroneri.lidarx"
    scripts:
      - name: Clean project
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" clean
      - name: Build and export .ipa
        script: |
          set -e
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_EXPORT_DIR/*.ipa
      - $CM_BUILD_DIR/xcarchive/*.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
