workflows:
  lidarx_ios:
    name: LiDarX iOS Build

    environment:
      groups:
        - LiDarX   # grupo criado no painel do Codemagic
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"
        XCODE_SCHEME: "LiDarX Agricultural"

    scripts:
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-configuration Release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
