workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      xcode: 16.4
      groups:
        - LiDarX
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"
        XCODE_SCHEME: "LiDarX Agricultural"
        BUNDLE_ID: "com.agroneri.lidarx"
    scripts:
      - name: Clean project
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" clean
      - name: Build and export .ipa
        script: |
          set -e
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-path "$CM_BUILD_DIR/LiDarX.xcarchive" \
            --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/LiDarX.xcarchive
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
