workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      groups:
        - LiDarX
    vars:
      XCODE_PROJECT: "LiDarX.xcodeproj"
      XCODE_SCHEME:  "LiDarX Agricultural"

    scripts:
      - name: Clean
        script: |
          #!/usr/bin/env bash
          set -e
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     clean

      - name: Build IPA
        script: |
          #!/usr/bin/env bash
          set -e
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive

    publishing:
      app_store_connect:
        # Sobe primeiro para o TestFlight
        submit_to_testflight: true
        beta_groups:
          - "Internal Testing"
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY


