workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      groups:
        - LiDarX
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"   # se usar Pods, trocaremos por .xcworkspace
        XCODE_SCHEME: "LiDarX Agricultural"
    scripts:
      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true
        api_key: $APP_STORE_CONNECT_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

