workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      groups:
        - LiDarX
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"
        XCODE_SCHEME: "LiDarX Agricultural"   # <— igual ao TARGET do pbxproj (com espaço)
    scripts:
      - name: Diagnóstico rápido
        script: |
          set -e
          echo "== xcodebuild -list =="
          xcodebuild -list -project "$XCODE_PROJECT" || true

      - name: Clean
        script: |
          set -e
          xcodebuild -project "$XCODE_PROJECT" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     clean

      - name: Build IPA
        script: |
          set -e
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive
      
publishing:
  app_store_connect:
    api_key:
      key_id: $APP_STORE_CONNECT_KEY_ID
      issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      private_key: $APP_STORE_CONNECT_PRIVATE_KEY
    testflight:
      submit: true
      beta_groups:
        - name: "Internal Testing"   # coloque aqui o nome exato do seu grupo
