workflows:
  lidarx_ios:
    name: LiDarX iOS Build
    environment:
      groups:
        - LiDarX
      vars:
        XCODE_PROJECT: "LiDarX.xcodeproj"
        XCODE_SCHEME:  "LiDarX Agricultural"

    scripts:
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        key_identifier: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_KEY
        submit_to_testflight: true
